### ISSUE TITLE
Tip: use define directive to allocate less memory

### ISSUE THREAD

**Issue by Gioela** [NekoMale/DataStructures#1]
In the main file, you can change the function _PrintNewSection()_ with the **#define** directive so, when you'll compile, you don't occupy registers with an object which does only a simple printf.

`#define PrintNewSection printf("------------------------\n")`
...
`

	ReverseList((ListHead)&linkedList);
	PrintList(linkedList);
	PrintNewSection;
`
..
[mainNekoMale.zip](https://github.com/NekoMale/DataStructures/files/7828478/mainNekoMale.zip)
.

**Comment by NekoMale** [comment]
Thank you so much. As I said, this is only an example file, so I didn't care about its performance or optimization.
